### ISSUE TITLE
Vorbereitung für die Semesterarbeit

### ISSUE THREAD

**Issue by Bazzako** [Euthal02/SemArb3_WeatherAPI#1]
- [x] Erstellung der eines neune Repositorys im Github
- [x] Erstellung der Task als Issues
- [x] Planung der Scrum meetings
- [x] Auswahl des Jekyll Tempate für Github Pages
- [x] Erstellung der CI/CD Pipeline für Github Pages
- [x] Erstellung der Ordnerstruktur
- [x] Grundgerüst der Dokumentation mit Github Pages bauen
- [x] Genauen Zeitplan definieren
- [x] Meilensteine erstellen

**Comment by Bazzako** [comment]
- [ ] Erstellung der eines neune Repositorys im Github
- [ ] Erstellung der Task als Issues
- [ ] Planung der Sprints
- [ ] Auswahl des Jekyll Tempate für Github Pages
- [ ] Erstellung der CI/CD Pipeline für Github Pages
- [ ] Erstellung der Ordnerstruktur
- [ ] Grundgerüst der Dokumentation mit Github Pages bauen
- [ ] Genauen Zeitplan definieren
- [ ] Meilensteine erstellen

**Comment by Euthal02** [comment]
- Das neue GitHub Repo wurde erstellt und ist hier zu finden: https://github.com/Euthal02/SemArb3_WeatherAPI
- Als Jekyll Template nutzen wir JustTheDocs: https://github.com/just-the-docs/just-the-docs
- Die CI/CD Pipeline für Github Pages wurde bereits erstellt und ist hier zu finden: https://github.com/Euthal02/SemArb3_WeatherAPI/blob/main/.github/workflows/jekyll-gh-pages.yml

**Comment by Euthal02** [comment]
- Die Ordnerstruktur der Dokumentationist erstellt und hier einsehbar: https://github.com/Euthal02/SemArb3_WeatherAPI/tree/main/docs

**Comment by Bazzako** [comment]
- Die Scrum Meetings wurden so festgelegt, dass ein Regelmässiger Austausch stattfinden kann

**Comment by Bazzako** [comment]
Der Genau Zeitplan wurde erstellt.
