### ISSUE TITLE
Scrum Meeting 1

### ISSUE THREAD

**Issue by Bazzako** [Euthal02/SemArb3_WeatherAPI#9]
Das ist die Planung für unser erstes Sprint Meeting. Wir werden an diesem Datum kurz besprechen, was wir bereits alles erledigen konnten und wie wir in unserem Projekt weitergehen werden.

**Comment by Euthal02** [comment]
Wir mussten das Meeting verschieben, da wir einige private Termine bereits hatten.
Die Erkenntisse findet ihr hier in unserer Doku.
https://euthal02.github.io/SemArb3_WeatherAPI/sprints/401-Sprint1.html
